-- Supabase entries 表结构
-- 请在 Supabase SQL Editor 中执行此脚本

-- 创建 entries 表
CREATE TABLE IF NOT EXISTS entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  content TEXT,
  date TEXT DEFAULT CURRENT_TIMESTAMP,
  mood TEXT,
  mood_emoji TEXT,
  weather TEXT,
  image_data TEXT
);

-- 启用 RLS (Row Level Security)
ALTER TABLE entries ENABLE ROW LEVEL SECURITY;

-- 创建允许匿名用户访问的策略
CREATE POLICY "Allow anonymous read" ON entries
  FOR SELECT USING (true);

CREATE POLICY "Allow anonymous insert" ON entries
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anonymous update" ON entries
  FOR UPDATE USING (true);

CREATE POLICY "Allow anonymous delete" ON entries
  FOR DELETE USING (true);